name: weather_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

    # --- Translations ---
  # Provides localization support for Flutter.
  easy_localization: ^3.0.7
  flutter_localizations:
    sdk: flutter

  # --- State Management ---
  # A predictable state management library based on the BLoC pattern.
  flutter_bloc: ^8.1.6

  # --- Service Locator ---
  # Dependency injection.
  get_it: ^8.0.2

  # --- Value Equality ---
  # Provides value equality for Dart objects.
  equatable: ^2.0.7

  # --- Functional Programming ---
  # A library for functional programming paradigms like Either and Option.
  dartz: ^0.10.1

  # --- Connectivity Check ---
  # Monitors internet connection status.
  internet_connection_checker_plus: ^2.5.2

  # --- API Client ---
  # A powerful HTTP client for Dart.
  dio: ^5.7.0

  # --- Responsive Design ---
  # Assists in creating responsive designs for different screen sizes.
  flutter_screenutil: ^5.9.3

  # --- Design ---
  # Adds carousel sliders.
  carousel_slider: ^5.0.0
  # Includes Cupertino design system icons.
  cupertino_icons: ^1.0.8

  # --- Cache and Database ---
  # Enables persistent storage of simple data.
  shared_preferences: ^2.3.3
  # Provides secure storage for sensitive data.
  flutter_secure_storage: ^9.2.2

  # --- SVG & Cached Images ---
  # Allows users to pick images from their device.
  image_picker: ^1.1.2
  # Renders SVG images in Flutter applications.
  flutter_svg: ^2.0.16

  # --- Firebase ---
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  firebase_messaging: ^15.1.5
  cloud_firestore: ^5.6.2
  # A Flutter package for showing loading animations.
  loading_animation_widget: ^1.3.0
  # --- Utilities ---
  # Provides spacing utilities.
  gap: ^3.0.1
  # Retrieves package-related information.
  logger: ^2.5.0
  # Offers internationalization and formatting utilities.
  intl: ^0.19.0
  # Native splash
  flutter_native_splash: ^2.4.4
  # location service
  geolocator: ^13.0.2
  geocoding: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/translations/ar-SA.json
    - assets/translations/en-US.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
